### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by probonopd** [Discord-Bot-Maker-Mods/DBM-Network-Client#12]
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir '/home/travis/.config/dbm-network-client/backups'
    at Object.mkdirSync (fs.js:731:3)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-8427/resources/app.asar/main.js:23:9)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-8427/resources/app.asar/main.js:241:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-8427/resources/electron.asar/browser/init.js:188:8)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-8427/resources/electron.asar/browser/init.js:190:3)
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/1404

**Comment by filipecarvalhodev** [comment]
Known issue and fixed (maybe)
